project:
  type: website

website:
  title: "Matthew Delgado"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Marketing Analytics"
        href: marketing-analytics.qmd
      - text: "Digital Marketing"
        href: digital-marketing.qmd
      - text: "Résumé"
        href: resume.qmd


format:
  html:
    theme: theme.scss
    toc: true
